version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lyrics
      POSTGRES_PASSWORD: lyrics
      POSTGRES_DB: lyrics_dev
    volumes: [db_data:/var/lib/postgresql/data]

  redis:
    image: redis:7

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes: ["./backend:/code"]
    env_file: ./backend/.env.dev
    depends_on: [db, redis]
    ports: ["8000:8000"]

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on: [backend]
    ports: ["3000:3000"]

volumes:
  db_data: